# Generated by Django 3.1.5 on 2021-01-18 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('Email_id', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(default='', max_length=100)),
                ('item_json', models.CharField(default='', max_length=10000)),
                ('name_on_card', models.CharField(max_length=100)),
                ('credit_card_number', models.CharField(max_length=50)),
                ('Exp_month', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=10)),
                ('Exp_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('pub_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='shippingaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mail_id', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderdetails')),
            ],
        ),
    ]
