# Generated by Django 3.1.5 on 2021-01-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210118_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='item_json',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
