# Generated by Django 3.1.5 on 2021-01-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210118_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Exp_month',
            field=models.CharField(max_length=50),
        ),
    ]
