# Generated by Django 3.1.5 on 2021-01-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210118_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
