# Generated by Django 3.1.5 on 2021-01-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderdetails_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
